import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase/client";

export async function POST(req: NextRequest) {
  try {
    const { message, conversationHistory } = await req.json();

    if (!message || !Array.isArray(conversationHistory)) {
      return NextResponse.json(
        { error: "Invalid request body. 'message' and 'conversationHistory' are required." },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY environment variable is not set." },
        { status: 500 }
      );
    }

    // Fetch approved servers from Supabase
    let servers = [];
    try {
      const { data, error } = await supabase
        .from("mcp_servers")
        .select("name,slug,description,category,install_command,config_snippet")
        .eq("approved", true);
      
      if (!error && data && data.length > 0) {
        servers = data;
      } else {
        const { FALLBACK_SERVERS } = await import("@/lib/supabase/fallback-data");
        servers = FALLBACK_SERVERS;
      }
    } catch (e) {
      console.warn("[Agent API] Supabase fetch failed, falling back to local seed data:", e);
      const { FALLBACK_SERVERS } = await import("@/lib/supabase/fallback-data");
      servers = FALLBACK_SERVERS;
    }

    // Format the list of servers for Gemini
    const serversList = servers.map(s => 
      `Server: ${s.name}
Slug: ${s.slug}
Category: ${s.category}
Description: ${s.description}
Install Command: ${s.install_command}
Config Snippet: ${s.config_snippet}`
    ).join("\n\n---\n\n");

    const systemPrompt = `You are an MCP Server Recommender for the MCPHub marketplace.
Your job is to help developers find the right Model Context Protocol (MCP) servers for their AI agents.
Here are all available MCP servers in the registry:

${serversList}

When a user describes what they want their agent to do:
1. Recommend the most relevant MCP servers from the registry ONLY. Only recommend servers that exist in the registry above.
2. Explain briefly what each one does.
3. Generate a ready-to-use combined config JSON code block that merges the config_snippets of all recommended servers. Format your config block exactly like the standard claude_desktop_config.json containing these servers (e.g. {"mcpServers": { ... }}).
4. Be concise and developer-friendly.`;

    // Map conversation history to Gemini format (role must be "user" or "model")
    const contents = [
      ...conversationHistory.map(m => ({
        role: m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content }]
      })),
      {
        role: "user",
        parts: [{ text: message }]
      }
    ];

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: {
            parts: [{ text: systemPrompt }]
          },
          contents
        })
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error("[Agent API] Gemini API error response:", errText);
      return NextResponse.json(
        { error: `Gemini API returned an error: ${response.statusText}` },
        { status: 502 }
      );
    }

    const data = await response.json();
    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!reply) {
      console.error("[Agent API] Empty reply from Gemini:", JSON.stringify(data));
      return NextResponse.json(
        { error: "No response generated by the AI model." },
        { status: 502 }
      );
    }

    return NextResponse.json({ reply });
  } catch (err) {
    console.error("[Agent API] Internal server error:", err);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}
